name: Java CI with Maven

on:
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize' ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: mvn clean install

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.0
        with:
          jacoco-csv-file: Tests/target/site/jacoco-aggregate/jacoco.csv
          generate-branches-badge: true

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain .github` ]]; then
                git branch
                git config --global user.name 'codecoverage'
                git config --global user.email 'codecoverage@wso2.com'
                git add .github
                git commit -m "Autogenerated JaCoCo coverage badge"
                git push origin HEAD:${{ github.head_ref }} --force
          fi
